Repository nasa/HS, pull requests merged in 2022-06, with the labels that each got.

#28 Fix #27, Remove CFE_PSP_MemSet use for addresses in RAM
  fsw/src/hs_app.c
  fsw/src/hs_cmds.c
  fsw/src/hs_monitors.c
  unit-test/hs_app_tests.c
  unit-test/utilities/hs_test_utils.c
Labels: CCB:Approved

#30 Fix #29, Updates CLA information for Apache 2.0
  .github/pull_request_template.md
  CONTRIBUTING.md
  docs/Corp_CLA_HS_240.pdf
  docs/Indv_CLA_HS_240.pdf
Labels: docs, CCB:Approved

#22 Fix #20, Added codeql-build.yml
  .github/workflows/codeql-build.yml
Labels: CCB:Approved, dependency

#34 Fix #12 #31 #32 #33, Coverage improvements
  .github/workflows/unit-test-coverage.yml
  fsw/src/hs_custom.c
  fsw/src/hs_custom.h
  fsw/src/hs_monitors.c
  unit-test/hs_cmds_tests.c
  unit-test/hs_custom_tests.c
  unit-test/hs_monitors_tests.c
  unit-test/utilities/hs_test_utils.c
Labels: CCB:Approved
